### ISSUE TITLE
EIP-155 compliant signatures for EIP-712 vouches are not handled properly

### ISSUE THREAD

**Issue by kdembler** [Proof-Of-Humanity/Proof-Of-Humanity#59]
Hey there!

I was looking at the PoH contract and found something potentially troublesome about the use of EIP-712 for vouches through signatures. The [code is requiring](https://github.com/Proof-Of-Humanity/Proof-Of-Humanity/blob/master/contracts/ProofOfHumanity.sol#L574) the `v` in the signature to be `27` or `28`. However, [according to the EIP-712 spec](https://eips.ethereum.org/EIPS/eip-712#returns), the `v` should be EIP-155 enabled - i.e. be of form `CHAIN_ID * 2 + 35`. That means, that given a valid EIP-712 signature, the contract might reject it, if it's replay attack protected.

Was this a conscious design decision for some reason or is it a bug?

**Comment by clesaege** [comment]
https://eips.ethereum.org/EIPS/eip-155 "The currently existing signature scheme using `v = 27` and `v = 28` remains valid and continues to operate under the same rules as it did previously."
So my understanding is that requiring `v` to be 27 or 28 is still acceptable.
But from EIP-155 "Note that the v parameter includes the chain id as specified in EIP-155." so this would actually mean that we would have needed to use the new `v` determination scheme.

Note that from a security perspective, we already have the chainID as part of the domain separator which makes it resistant to cross-networking replay https://github.com/Proof-Of-Humanity/Proof-Of-Humanity/blob/master/contracts/ProofOfHumanity.sol#L285 so this is only about standardization.

Do you have an example of contracts using the new `v` determination scheme?
I reviewed quite a bunch of contracts using ECDSA signatures and from what I can remember they were all requiring `v` to be 27 or 28.
Ex: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol

**Comment by kdembler** [comment]
Unfortunately, I don't have an example of a contract using this scheme. Your example from OpenZeppelin confused me at first as well, but after giving it some thought, it seems to make sense. If you follow Appendix F of the [yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf), it specifies that the ECDSA signature is valid _only_ with `v` of 27 and 28. However, reading further, it also tells you that when recovering the message signer, you shouldn't use the `v` directly, but rather do some "preprocessing" of it:
<img width="893" alt="Screenshot 2021-04-23 at 17 45 38" src="https://user-images.githubusercontent.com/12646744/115896447-bc1e1780-a45b-11eb-8b78-497ab20047d0.png">

So having above in mind, you could probably say that signature using EIP-155 scheme isn't supposed to be a valid ECDSA signature directly but rather tell you how to validate `chainId` correctness and how to extract ECDSA signature out of it (`v(ECDSA) = 28 - v(SIG) % 2`). That would explain why the OpenZeppelin utility doesn't care about values other than 27 and 28 - it implements only the ECDSA recovery. If you want to conform to EIP-155, it needs to happen on a higher level.

Coming back to EIP-712, it states that:

> Note that the v parameter includes the chain id as specified in EIP-155.

With that in mind, you could argue that `v` with value of 27 and 28 isn't a valid EIP-712 signature at all (it doesn't use EIP-155). However, it probably doesn't hurt to allow them as well, since as you mentioned, the separator will already specify the chain ID. Although, the other values should probably be allowed as well, to follow the spec.

Curious what you think

**Comment by kdembler** [comment]
Thinking about security aspect some more, you could argue that the chain ID in the separator may not be as good of a security guarantee as `v` in the signature. That's because it's part of the signed message itself and a malicious application could construct a message for a different chain without user being aware of it. Think about doing something on BSC and the app you're using creating a message with chain ID of ETH mainnet in the separator. The user would get a prompt from their signer to sign a message for BSC (their currently selected chain), but the app could use that effectively on ETH mainnet if `v` is not further validated. If the guarantee of a replay protection comes from a signer app instead, it's probably a better one.

This is highly hypothetical of course, but worth thinking about I believe

**Comment by clesaege** [comment]
Yeah, I agree.
Well now it's deployed and it doesn't lead to security issues so I'll close the issue but feel free to report that in the EIP-155 to see if other people had the same reading of it as you had (which I believe is correct even if it conflicts with all the implementations I've seen so far).
